### ISSUE TITLE
PRs updated via `tibdex/auto-update` don't trigger certain required checks

### ISSUE THREAD

**Issue by inxilpro** [tibdex/auto-update#13]
We have a CI workflow that is triggered by:

```yml
on:
  pull_request_target:
    types: [ opened, synchronize, reopened, ready_for_review ]
  push:
    branches:
      - production
```

We also have a CircleCI workflow configured via the "CircleCI Checks" GitHub app.

If I go into the GitHub web interface and click the "Update Branch" button, all my workflows are triggered. If, instead, I enable Auto-Merge and let `tibdex/auto-update` trigger the update, only my CircleCI workflow runs. The GitHub actions just show "Expected — Waiting for status to be reported" but never trigger.

Is this something you have run into? Any idea how to get GitHub to trigger my CI workflow when this action triggers an update?
